data: ../KETI_oneweek
log: ./logs/
# FFT config
window_size: 200
k_coefficient: 32
stride: 20     
interval: 5
max_length: 130000
# CNN config
epoch: 1
batch_size: 32
optim: 'SGD'
learning_rate: 0.0001
dropout: 0.2
grad_norm: 0
weight_decay: 0.0001
